Repository openshift-knative/knative-istio-authz-chart, pull requests merged in 2023-07, with the labels that each got.

#2 When is an array
  templates/allow-knative-to-ns.yaml
  templates/allow-ns-to-kafka-broker-reply.yaml
  templates/allow-ns-to-mt-channel-based-broker-reply.yaml
  templates/allow-to-knative-eventing-receiver.yaml
  templates/allow-to-knative-serving-receiver.yaml
Labels: lgtm

#5 Add OWNERS copied from SO
  OWNERS
  OWNERS_ALIASES
Labels: lgtm

#6 Update README to use openshift-knative image instead of mine
  README.md
Labels: lgtm

#1 Add serving resources to helm chart
  .gitignore
  README.md
  setup/allow-mt-channel-based-broker-to-channels.yaml
  setup/allow-probe-kafka-controller.yaml
  setup/allow-traffic-to-activator.yaml
  setup/allow-traffic-to-autoscaler.yaml
  setup/deny-all-by-default.yaml
  templates/common-allow-knative-to-ns.yaml
  templates/common-allow-via-knative-serving.yaml
  templates/eventing-allow-ns-to-kafka-broker-reply.yaml
  templates/eventing-allow-ns-to-mt-channel-based-broker-reply.yaml
  templates/eventing-allow-to-knative-eventing-receiver.yaml
  templates/peer-authentication.yaml
  templates/serving-allow-wait-for-drain.yaml
  values.yaml
Labels: approved

#7 Eventing: Remove POST only requests and add all host variants
  templates/common-allow-via-knative-serving.yaml
  templates/eventing-allow-ns-to-kafka-broker-reply.yaml
  templates/eventing-allow-ns-to-mt-channel-based-broker-reply.yaml
  templates/eventing-allow-to-knative-eventing-receiver.yaml
Labels: lgtm, approved
